<?php

$jackkills = array(
"kill 1"=> array("Season Total"=>"1",
				"name"=>"Ira Gaines hitman #1",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"SIG P228 with silencer"),
"kill 2"=> array("Season Total"=>"2",
				"name"=>"Ira Gaines hitman #2",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"SIG P228 with silencer"),
"kill 3"=> array("Season Total"=>"3",
				"name"=>"Ted Cofell",
				"episode"=>"10:00am-11:00am",
				"weapon"=>"Punch to the heart"),
"kill 4"=> array("Season Total"=>"4",
				"name"=>"Ira Gaines terrorist #1",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"Van explosion"),
"kill 5"=> array("Season Total"=>"5",
				"name"=>"Ira Gaines terrorist #2",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"Van explosion"),
"kill 6"=> array("Season Total"=>"6",
				"name"=>"Neil Nagi",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"SIG P228 with silencer"),
"kill 7"=> array("Season Total"=>"7",
				"name"=>"Ira Gaines",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"SIG P228 with silencer"),
"kill 8"=> array("Season Total"=>"8",
				"name"=>"Marko",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"HK USP x 2"),
"kill 9"=> array("Season Total"=>"9",
				"name"=>"Andre Drazen",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"HK USP x 2"),
"kill 10"=> array("Season Total"=>"10",
				"name"=>"Victor Drazen",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"HK USP"),
"kill 11"=> array("Season Total"=>"1",
				"name"=>"Marshall Goren",
				"episode"=>"8:00am-9:00am",
				"weapon"=>"Beretta M92FS"),
"kill 12"=> array("Season Total"=>"2",
				"name"=>"Scott",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"S&W 60 and Beretta M92FS Inox"),
"kill 13"=> array("Season Total"=>"3",
				"name"=>"Chris",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"S&W 60 and Beretta M92FS Inox"),
"kill 14"=> array("Season Total"=>"4",
				"name"=>"Eddie Grant",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"Beretta M92FS Inox"),
"kill 15"=> array("Season Total"=>"5",
				"name"=>"Mamud Faheen terrorist",
				"episode"=>"2:00pm-3:00pm",
				"weapon"=>"SIG P228"),
"kill 16"=> array("Season Total"=>"6",
				"name"=>"Coral Snake soldier #1",
				"episode"=>"4:00pm-5:00pm",
				"weapon"=>"HK P2A1"),
"kill 17"=> array("Season Total"=>"7",
				"name"=>"Coral Snake soldier #2",
				"episode"=>"4:00pm-5:00pm",
				"weapon"=>"M4A1 Carabine"),
"kill 18"=> array("Season Total"=>"8",
				"name"=>"Coral Snake soldier #3",
				"episode"=>"4:00pm-5:00pm",
				"weapon"=>"M4A1 Carabine"),
"kill 19"=> array("Season Total"=>"9",
				"name"=>"Coral Snake soldier #4",
				"episode"=>"4:00pm-5:00pm",
				"weapon"=>"M4A1 Carabine"),
"kill 20"=> array("Season Total"=>"10",
				"name"=>"Peter Kingsley hitman #1",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"SIG P228"),
"kill 21"=> array("Season Total"=>"11",
				"name"=>"Peter Kingsley hitman #2",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"SIG P228"),
"kill 22"=> array("Season Total"=>"12",
				"name"=>"Peter Kingsley hitman #3",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"SIG P228"),
"kill 23"=> array("Season Total"=>"13",
				"name"=>"Peter Kingsley hitman #4",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"SIG P228"),
"kill 24"=> array("Season Total"=>"14",
				"name"=>"Peter Kingsley hitman #5",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"Mac-10"),
"kill 25"=> array("Season Total"=>"15",
				"name"=>"Peter Kingsley hitman #6",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"Mac-10"),
"kill 26"=> array("Season Total"=>"16",
				"name"=>"Peter Kingsley hitman #7",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"Mac-10"),
"kill 27"=> array("Season Total"=>"17",
				"name"=>"Peter Kingsley hitman #8",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"Mac-10"),
"kill 28"=> array("Season Total"=>"18",
				"name"=>"Peter Kingsley hitman #9",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"SIG P228"),
"kill 29"=> array("Season Total"=>"19",
				"name"=>"Ronnie Stark thug",
				"episode"=>"2:00am-3:00am",
				"weapon"=>"SIG P228"),
"kill 30"=> array("Season Total"=>"20",
				"name"=>"Davis",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP with silencer"),
"kill 31"=> array("Season Total"=>"21",
				"name"=>"Trask",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP with silencer"),
"kill 32"=> array("Season Total"=>"22",
				"name"=>"Raymond O'Hara",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP with silencer"),
"kill 33"=> array("Season Total"=>"23",
				"name"=>"Rouse",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP with silencer"),
"kill 34"=> array("Season Total"=>"24",
				"name"=>"Alex Hewitt",
				"episode"=>"6:00am-7:00am",
				"weapon"=>"Head impact"),
"kill 35"=> array("Season Total"=>"25",
				"name"=>"Scott",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"Unknown"),
"kill 36"=> array("Season Total"=>"26",
				"name"=>"Peter Kingsley thug #1",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"HK SR9T"),
"kill 37"=> array("Season Total"=>"27",
				"name"=>"Peter Kingsley thug #2",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"HK SR9T"),
"kill 38"=> array("Season Total"=>"28",
				"name"=>"Peter Kingsley thug #3",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"HK SR9T"),
"kill 39"=> array("Season Total"=>"29",
				"name"=>"Peter Kingsley thug #4",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"HK SR9T"),
"kill 40"=> array("Season Total"=>"30",
				"name"=>"Peter Kingsley thug #5",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"Broken neck"),
"kill 41"=> array("Season Total"=>"1",
				"name"=>"Peel",
				"episode"=>"5:00pm-6:00pm",
				"weapon"=>"S&W 66"),
"kill 42"=> array("Season Total"=>"2",
				"name"=>"Pedro",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"Broken Neck"),
"kill 43"=> array("Season Total"=>"3",
				"name"=>"Nina Myers guard #1",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Beretta M92FS"),
"kill 44"=> array("Season Total"=>"4",
				"name"=>"Nina Myers guard #2",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Beretta M92FS"),
"kill 45"=> array("Season Total"=>"5",
				"name"=>"Nina Myers guard #3",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Beretta M92FS"),
"kill 46"=> array("Season Total"=>"6",
				"name"=>"Ramon Salazar thug #1",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"Massad Ayoob Razorback"),
"kill 47"=> array("Season Total"=>"7",
				"name"=>"Ramon Salazar thug #2",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"Massad Ayoob Razorback"),
"kill 48"=> array("Season Total"=>"8",
				"name"=>"Ramon Salazar thug #3",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"Massad Ayoob Razorback"),
"kill 49"=> array("Season Total"=>"9",
				"name"=>"Nina Myers",
				"episode"=>"2:00am-3:00am",
				"weapon"=>"Beretta M92FS"),
"kill 50"=> array("Season Total"=>"10",
				"name"=>"Michael Amador guard",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP Compact"),
"kill 51"=> array("Season Total"=>"11",
				"name"=>"Pach ",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 52"=> array("Season Total"=>"12",
				"name"=>"Young",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 53"=> array("Season Total"=>"13",
				"name"=>"Ryan Chappelle",
				"episode"=>"6:00am-7:00am",
				"weapon"=>"HK USP Compact"),
"kill 54"=> array("Season Total"=>"14",
				"name"=>"Arthur Rabens",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact"),
"kill 55"=> array("Season Total"=>"1",
				"name"=>"Kalil Hasan thug #1",
				"episode"=>"9:00am-10:00am",
				"weapon"=>"Accuracy International AWP"),
"kill 56"=> array("Season Total"=>"2",
				"name"=>"Kalil Hasan thug #2",
				"episode"=>"9:00am-10:00am",
				"weapon"=>"Accuracy International AWP"),
"kill 57"=> array("Season Total"=>"3",
				"name"=>"Compound terrorist #1",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"Broken neck"),
"kill 58"=> array("Season Total"=>"4",
				"name"=>"Compound terrorist #2",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 59"=> array("Season Total"=>"5",
				"name"=>"Compound terrorist #3",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 60"=> array("Season Total"=>"6",
				"name"=>"Compound terrorist #4",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 61"=> array("Season Total"=>"7",
				"name"=>"Compound terrorist #5",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 62"=> array("Season Total"=>"8",
				"name"=>"Compound terrorist #6",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 63"=> array("Season Total"=>"9",
				"name"=>"Kevin",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 64"=> array("Season Total"=>"10",
				"name"=>"Compound terrorist #7",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 65"=> array("Season Total"=>"11",
				"name"=>"Compound terrorist #8",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"AK-47"),
"kill 66"=> array("Season Total"=>"12",
				"name"=>"Compound terrorist #9",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 67"=> array("Season Total"=>"13",
				"name"=>"Compound terrorist #10",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 68"=> array("Season Total"=>"14",
				"name"=>"Henry Powell hitman #1",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"HK USP Compact"),
"kill 69"=> array("Season Total"=>"15",
				"name"=>"Henry Powell hitman #2",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"HK USP Compact"),
"kill 70"=> array("Season Total"=>"16",
				"name"=>"Henry Powell hitman #3",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"HK USP Compact"),
"kill 71"=> array("Season Total"=>"17",
				"name"=>"Henry Powell hitman #4",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"HK USP Compact"),
"kill 72"=> array("Season Total"=>"18",
				"name"=>"Henry Powell hitman #5",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"Beretta M92FS with silencer"),
"kill 73"=> array("Season Total"=>"19",
				"name"=>"McLennen-Forster security guard",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"HK USP Compact"),
"kill 74"=> array("Season Total"=>"20",
				"name"=>"James",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"HK USP Compact"),
"kill 75"=> array("Season Total"=>"21",
				"name"=>"Stevens",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"HK USP Compact"),
"kill 76"=> array("Season Total"=>"22",
				"name"=>"McLennen-Forster commando #1",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"Ruger Mini-14"),
"kill 77"=> array("Season Total"=>"23",
				"name"=>"McLennen-Forster commando #2",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"Ruger Mini-14"),
"kill 78"=> array("Season Total"=>"24",
				"name"=>"McLennen-Forster commando #3",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"Ruger Mini-14"),
"kill 79"=> array("Season Total"=>"25",
				"name"=>"McLennen-Forster commando #4",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"Mossberg 590 Mariner"),
"kill 80"=> array("Season Total"=>"26",
				"name"=>"Specter",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"Microtech Halo III to back of neck"),
"kill 81"=> array("Season Total"=>"27",
				"name"=>"Dave Conlon",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"HK USP Compact"),
"kill 82"=> array("Season Total"=>"28",
				"name"=>"Warehouse terrorist #1",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 83"=> array("Season Total"=>"29",
				"name"=>"Warehouse terrorist #2",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 84"=> array("Season Total"=>"30",
				"name"=>"Warehouse terrorist #3",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 85"=> array("Season Total"=>"31",
				"name"=>"Warehouse terrorist #4",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Microtech Halo III"),
"kill 86"=> array("Season Total"=>"32",
				"name"=>"Warehouse terrorist #5",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 87"=> array("Season Total"=>"33",
				"name"=>"Warehouse terrorist #6",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 88"=> array("Season Total"=>"34",
				"name"=>"Warehouse terrorist #7",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 89"=> array("Season Total"=>"35",
				"name"=>"Warehouse terrorist #8",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 90"=> array("Season Total"=>"36",
				"name"=>"Nicole",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 91"=> array("Season Total"=>"37",
				"name"=>"Abdul Mahnesh",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"HK USP Compact"),
"kill 92"=> array("Season Total"=>"38",
				"name"=>"Habib Marwan thug",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"HK USP Compact"),
"kill 93"=> array("Season Total"=>"39",
				"name"=>"Steve Simmons",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"HK USP Compact"),
"kill 94"=> array("Season Total"=>"40",
				"name"=>"Hikmat Palpatine",
				"episode"=>"1:00am-2:00am",
				"weapon"=>"HK USP Compact"),
"kill 95"=> array("Season Total"=>"41",
				"name"=>"Paul Raines",
				"episode"=>"2:00am-3:00am",
				"weapon"=>"Interrupted surgery"),
"kill 96"=> array("Season Total"=>"42",
				"name"=>"Yassir",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP Compact"),
"kill 97"=> array("Season Total"=>"43",
				"name"=>"Marwan's chopper pilot",
				"episode"=>"6:00am-7:00am",
				"weapon"=>"HK USP Compact"),
"kill 98"=> array("Season Total"=>"1",
				"name"=>"Kohler",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"Microtech HALO III"),
"kill 99"=> array("Season Total"=>"2",
				"name"=>"Haas mercenary #1",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"HK USP Compact"),
"kill 100"=> array( "Season Total"=>"3",
				"name"=>"Haas mercenary #2",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"HK USP Compact"),
"kill 101"=> array( "Season Total"=>"4",
				"name"=>"Conrad Haas",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"HK USP Compact"),
"kill 102"=> array( "Season Total"=>"5",
				"name"=>"Ibrim",
				"episode"=>"9:00am-10:00am",
				"weapon"=>"Explosive vest"),
"kill 103"=> array( "Season Total"=>"6",
				"name"=>"Beresch separatist #1",
				"episode"=>"9:00am-10:00am",
				"weapon"=>"Explosive vest"),
"kill 104"=> array( "Season Total"=>"7",
				"name"=>"Vlad",
				"episode"=>"10:00am-11:00am",
				"weapon"=>"SIG P225"),
"kill 105"=> array( "Season Total"=>"8",
				"name"=>"Beresch separatist #2",
				"episode"=>"10:00am-11:00am",
				"weapon"=>"SIG P225"),
"kill 106"=> array( "Season Total"=>"9",
				"name"=>"Hank",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"Scissors"),
"kill 107"=> array( "Season Total"=>"10",
				"name"=>"Penthouse security guard #1",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"HK USP Compact"),
"kill 108"=> array( "Season Total"=>"11",
				"name"=>"Penthouse security guard #2",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"HK USP Compact"),
"kill 109"=> array( "Season Total"=>"12",
				"name"=>"Komar",
				"episode"=>"2:00pm-3:00pm",
				"weapon"=>"Broken neck"),
"kill 110"=> array( "Season Total"=>"13",
				"name"=>"Ostroff separatist #1",
				"episode"=>"3:00pm-4:00pm",
				"weapon"=>"HK USP Compact"),
"kill 111"=> array( "Season Total"=>"14",
				"name"=>"Ostroff separatist #2",
				"episode"=>"3:00pm-4:00pm",
				"weapon"=>"HK USP Compact"),
"kill 112"=> array( "Season Total"=>"15",
				"name"=>"Ostroff",
				"episode"=>"6:00pm-7:00pm",
				"weapon"=>"HK USP Compact"),
"kill 113"=> array( "Season Total"=>"16",
				"name"=>"Bierko separatist #1",
				"episode"=>"9:00pm-10:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 114"=> array( "Season Total"=>"17",
				"name"=>"Bierko separatist #2",
				"episode"=>"9:00pm-10:00pm",
				"weapon"=>"HK USP Compact"),
"kill 115"=> array( "Season Total"=>"18",
				"name"=>"Bierko separatist #3",
				"episode"=>"9:00pm-10:00pm",
				"weapon"=>"HK USP Compact"),
"kill 116"=> array( "Season Total"=>"19",
				"name"=>"Mikhail",
				"episode"=>"9:00pm-10:00pm",
				"weapon"=>"HK USP Compact"),
"kill 117"=> array( "Season Total"=>"20",
				"name"=>"Henderson mercenary #1",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 118"=> array( "Season Total"=>"21",
				"name"=>"Henderson mercenary #2",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 119"=> array( "Season Total"=>"22",
				"name"=>"Brennan",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Benchmade 9130 Auto Stryker"),
"kill 120"=> array( "Season Total"=>"23",
				"name"=>"Henderson mercenary #3",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK SL8"),
"kill 121"=> array( "Season Total"=>"24",
				"name"=>"Henderson mercenary #4",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK SL8"),
"kill 122"=> array( "Season Total"=>"25",
				"name"=>"Cooper mercenary #1",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"HK USP Compact"),
"kill 123"=> array( "Season Total"=>"26",
				"name"=>"Cooper mercenary #2",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"HK USP Compact"),
"kill 124"=> array( "Season Total"=>"27",
				"name"=>"Cooper mercenary #3",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"HK USP Compact"),
"kill 125"=> array( "Season Total"=>"28",
				"name"=>"Henderson mercenary #5",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"HK USP Compact"),
"kill 126"=> array( "Season Total"=>"29",
				"name"=>"Henderson mercenary #6",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"HK USP Compact"),
"kill 127"=> array( "Season Total"=>"30",
				"name"=>"Henderson mercenary #7",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"HK USP Compact"),
"kill 128"=> array( "Season Total"=>"31",
				"name"=>"Henderson mercenary #8",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"Explosion"),
"kill 129"=> array( "Season Total"=>"32",
				"name"=>"Henderson mercenary #9",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"Explosion"),
"kill 130"=> array( "Season Total"=>"33",
				"name"=>"Henderson mercenary #10",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"Explosion"),
"kill 131"=> array( "Season Total"=>"34",
				"name"=>"Vladimir Bierko separatist #4",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 132"=> array( "Season Total"=>"35",
				"name"=>"Bierko's technician",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Microtech Makora"),
"kill 133"=> array( "Season Total"=>"36",
				"name"=>"Vladimir Bierko separatist #5",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 134"=> array( "Season Total"=>"37",
				"name"=>"Vladimir Bierko separatist #6",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Steam Burn"),
"kill 135"=> array( "Season Total"=>"38",
				"name"=>"Vladimir Bierko",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Broken neck"),
"kill 136"=> array( "Season Total"=>"39",
				"name"=>"Christopher Henderson",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 137"=> array( "Season Total"=>"1",
				"name"=>"Fayed terrorist #1",
				"episode"=>"6:00am-7:00am",
				"weapon"=>"Teeth"),
"kill 138"=> array( "Season Total"=>"2",
				"name"=>"Curtis Manning",
				"episode"=>"9:00am-10:00am",
				"weapon"=>"HK USP Compact"),
"kill 139"=> array( "Season Total"=>"3",
				"name"=>"Irv",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"SIG Sauer P229R"),
"kill 140"=> array( "Season Total"=>"4",
				"name"=>"Fayed terrorist #2",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"Mossberg 590"),
"kill 141"=> array( "Season Total"=>"5",
				"name"=>"Fayed terrorist #3",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"Mossberg 590"),
"kill 142"=> array( "Season Total"=>"6",
				"name"=>"Kozelek Hacker mercenary",
				"episode"=>"3:00pm-4:00pm",
				"weapon"=>"HK USP Compact"),
"kill 143"=> array( "Season Total"=>"7",
				"name"=>"Ed",
				"episode"=>"3:00pm-4:00pm",
				"weapon"=>"HK USP Compact"),
"kill 144"=> array( "Season Total"=>"8",
				"name"=>"Vasili",
				"episode"=>"6:00pm-7:00pm",
				"weapon"=>"Makarov PM"),
"kill 145"=> array( "Season Total"=>"9",
				"name"=>"Russian consulate guard #1",
				"episode"=>"6:00pm-7:00pm",
				"weapon"=>"Makarov PM"),
"kill 146"=> array( "Season Total"=>"10",
				"name"=>"Russian consulate guard #2",
				"episode"=>"6:00pm-7:00pm",
				"weapon"=>"Makarov PM"),
"kill 147"=> array( "Season Total"=>"11",
				"name"=>"Victor's terrorist #1",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 148"=> array( "Season Total"=>"12",
				"name"=>"Victor's terrorist #2",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 149"=> array( "Season Total"=>"13",
				"name"=>"Victor",
				"episode"=>"8:00pm-9:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 150"=> array( "Season Total"=>"14",
				"name"=>"Gredenko's terrorist",
				"episode"=>"8:00pm-9:00pm",
				"weapon"=>"HK USP Compact"),
"kill 151"=> array( "Season Total"=>"15",
				"name"=>"Hasan",
				"episode"=>"9:00pm-10:00pm",
				"weapon"=>"HK USP Compact"),
"kill 152"=> array( "Season Total"=>"16",
				"name"=>"Hasim",
				"episode"=>"9:00pm-10:00pm",
				"weapon"=>"HK USP Compact"),
"kill 153"=> array( "Season Total"=>"17",
				"name"=>"Fayed terrorist #4",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Broken neck"),
"kill 154"=> array( "Season Total"=>"18",
				"name"=>"Fayed terrorist #5",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 155"=> array( "Season Total"=>"19",
				"name"=>"Fayed terrorist #6",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 156"=> array( "Season Total"=>"20",
				"name"=>"Fayed terrorist #7",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 157"=> array( "Season Total"=>"21",
				"name"=>"Fayed terrorist #8",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 158"=> array( "Season Total"=>"22",
				"name"=>"Halil",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 159"=> array( "Season Total"=>"23",
				"name"=>"Fayed terrorist #9",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 160"=> array( "Season Total"=>"24",
				"name"=>"Abu Fayed",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Hanging with chain"),
"kill 161"=> array( "Season Total"=>"25",
				"name"=>"Cheng Zhi operative #1",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"HK USP Compact"),
"kill 162"=> array( "Season Total"=>"26",
				"name"=>"Cheng Zhi operative #2",
				"episode"=>"12:00am-1:00am",
				"weapon"=>"HK USP Compact"),
"kill 163"=> array( "Season Total"=>"27",
				"name"=>"Zhou commando #1",
				"episode"=>"2:00am-3:00am",
				"weapon"=>"Beretta Px4 Storm"),
"kill 164"=> array( "Season Total"=>"28",
				"name"=>"Zhou commando #2",
				"episode"=>"2:00am-3:00am",
				"weapon"=>"Beretta Px4 Storm"),
"kill 165"=> array( "Season Total"=>"29",
				"name"=>"Zhou commando #3",
				"episode"=>"2:00am-3:00am",
				"weapon"=>"Beretta Px4 Storm"),
"kill 166"=> array( "Season Total"=>"30",
				"name"=>"Zhou commando #4",
				"episode"=>"2:00am-3:00am",
				"weapon"=>"HK G36C Carbine"),
"kill 167"=> array( "Season Total"=>"31",
				"name"=>"Zhou commando #5",
				"episode"=>"2:00am-3:00am",
				"weapon"=>"HK G36C Carbine"),
"kill 168"=> array( "Season Total"=>"32",
				"name"=>"Zhou commando #6",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK G36C Carbine"),
"kill 169"=> array( "Season Total"=>"33",
				"name"=>"Zhou Yong",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"Broken Neck"),
"kill 170"=> array( "Season Total"=>"34",
				"name"=>"Cheng Zhi operative #3",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP Compact"),
"kill 171"=> array( "Season Total"=>"35",
				"name"=>"Cheng Zhi operative #4",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP Compact"),
"kill 172"=> array( "Season Total"=>"36",
				"name"=>"Cheng's operative",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP Compact"),
"kill 173"=> array( "Season Total"=>"37",
				"name"=>"Zhou commando #8",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP Compact"),
"kill 174"=> array( "Season Total"=>"38",
				"name"=>"Zhou's lieutenant",
				"episode"=>"3:00am-4:00am",
				"weapon"=>"HK USP Compact"),
"kill 175"=> array( "Season Total"=>"39",
				"name"=>"Oil rig operative #1",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK MP7A1 PDW"),
"kill 176"=> array( "Season Total"=>"40",
				"name"=>"Oil rig operative #2",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK MP7A1 PDW"),
"kill 177"=> array( "Season Total"=>"41",
				"name"=>"Oil rig operative #3",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK MP7A1 PDW"),
"kill 178"=> array( "Season Total"=>"42",
				"name"=>"Oil rig operative #4",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Explosion"),
"kill 179"=> array( "Season Total"=>"43",
				"name"=>"Oil rig operative #5",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Explosion"),
"kill 180"=> array( "Season Total"=>"44",
				"name"=>"Oil rig operative #6",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Explosion"),
"kill 181"=> array( "Season Total"=>"45",
				"name"=>"Oil rig operative #7",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Explosion"),
"kill 182"=> array( "Season Total"=>"46",
				"name"=>"Oil rig operative #8",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Explosion"),
"kill 183"=> array( "Season Total"=>"47",
				"name"=>"Oil rig operative #9",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Explosion"),
"kill 184"=> array( "Season Total"=>"48",
				"name"=>"Oil rig operative #10",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Explosion"),
"kill 185"=> array( "Season Total"=>"49",
				"name"=>"Oil rig operative #11",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"Explosion"),
"kill 186"=> array( "Season Total"=>"50",
				"name"=>"Phillip Bauer mercenary #1",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 187"=> array( "Season Total"=>"51",
				"name"=>"Phillip Bauer mercenary #2",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),

"kill 188"=> array( "Season Total"=>"1",
				"name"=>"Rebel Soldier #1", 
				"episode"=>"Redemption",
				"weapon"=>"Explosion"),
"kill 189"=> array( "Season Total"=>"2",
				"name"=>"Rebel Soldier #2", 
				"episode"=>"Redemption",
				"weapon"=>"Explosion"),
"kill 190"=> array( "Season Total"=>"3",
				"name"=>"Rebel Soldier #3", 
				"episode"=>"Redemption",
				"weapon"=>"Glock 19"),
"kill 191"=> array( "Season Total"=>"4",
				"name"=>"Rebel Soldier #4", 
				"episode"=>"Redemption",
				"weapon"=>"Glock 19"),
"kill 192"=> array( "Season Total"=>"5",
				"name"=>"Rebel Soldier #5", 
				"episode"=>"Redemption",
				"weapon"=>"Glock 19"),
"kill 193"=> array( "Season Total"=>"6",
				"name"=>"Rebel Soldier #6", 
				"episode"=>"Redemption",
				"weapon"=>"Glock 19"),
"kill 194"=> array( "Season Total"=>"7",
				"name"=>"Rebel Soldier #7", 
				"episode"=>"Redemption",
				"weapon"=>"Glock 19"),
"kill 195"=> array( "Season Total"=>"8",
				"name"=>"Rebel Soldier #8", 
				"episode"=>"Redemption",
				"weapon"=>"Ontario 102 spec tactical hunter"),
"kill 196"=> array( "Season Total"=>"9",
				"name"=>"Rebel Soldier #9", 
				"episode"=>"Redemption",
				"weapon"=>"AKMS-47"),
"kill 197"=> array( "Season Total"=>"10",
				"name"=>"Rebel Soldier #10", 
				"episode"=>"Redemption",
				"weapon"=>"TNT Explosive"),
"kill 198"=> array( "Season Total"=>"11",
				"name"=>"Rebel Soldier #11", 
				"episode"=>"Redemption",
				"weapon"=>"AKMS-47"),
"kill 199"=> array( "Season Total"=>"12",
				"name"=>"Youssou Dubaku", 
				"episode"=>"Redemption",
				"weapon"=>"Broken neck"),
"kill 200"=> array( "Season Total"=>"13",
				"name"=>"Rebel Soldier #12", 
				"episode"=>"Redemption",
				"weapon"=>"Glock 19"),
"kill 201"=> array( "Season Total"=>"14",
				"name"=>"Rebel Soldier #13", 
				"episode"=>"Redemption",
				"weapon"=>"Glock 19"),
"kill 202"=> array( "Season Total"=>"15",
				"name"=>"Rebel Soldier #14", 
				"episode"=>"Redemption",
				"weapon"=>"Glock 19"),

"kill 203"=> array( "Season Total"=>"1",
				"name"=>"Masters",
				"episode"=>"9:00am-10:00am",
				"weapon"=>"HK USP Compact"),
"kill 204"=> array( "Season Total"=>"2",
				"name"=>"Nichols' bodyguard",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"ASW338LM"),
"kill 205"=> array( "Season Total"=>"3",
				"name"=>"Nichols' mercenary #1",
				"episode"=>"2:00pm-3:00pm",
				"weapon"=>"Explosive device"),
"kill 206"=> array( "Season Total"=>"4",
				"name"=>"Nichols' mercenary #2",
				"episode"=>"2:00pm-3:00pm",
				"weapon"=>"HK USP Compact"),
"kill 207"=> array( "Season Total"=>"5",
				"name"=>"Nichols' mercenary #3",
				"episode"=>"2:00pm-3:00pm",
				"weapon"=>"HK USP Compact"),
"kill 208"=> array( "Season Total"=>"6",
				"name"=>"Nichols' mercenary #4",
				"episode"=>"2:00pm-3:00pm",
				"weapon"=>"HK USP Compact"),
"kill 209"=> array( "Season Total"=>"7",
				"name"=>"Nichols' mercenary #5",
				"episode"=>"2:00pm-3:00pm",
				"weapon"=>"HK MP7"),
"kill 210"=> array( "Season Total"=>"8",
				"name"=>"Nichols' mercenary #6",
				"episode"=>"2:00pm-3:00pm",
				"weapon"=>"HK MP7"),
"kill 211"=> array( "Season Total"=>"9",
				"name"=>"Nichols' mercenary #7",
				"episode"=>"2:00pm-3:00pm",
				"weapon"=>"HK MP7"),
"kill 212"=> array( "Season Total"=>"10",
				"name"=>"Edward Vossler",
				"episode"=>"3:00pm-4:00pm",
				"weapon"=>"DKW Sandshark to the stomach"),
"kill 213"=> array( "Season Total"=>"11",
				"name"=>"Store clerk working with Dubaku",
				"episode"=>"3:00pm-4:00pm",
				"weapon"=>"Blow to head with a HK USP Compact"),
"kill 214"=> array( "Season Total"=>"12",
				"name"=>"Dubaku's henchman #1",
				"episode"=>"3:00pm-4:00pm",
				"weapon"=>"HK USP Compact"),
"kill 215"=> array( "Season Total"=>"13",
				"name"=>"Dubaku's henchman #2",
				"episode"=>"3:00pm-4:00pm",
				"weapon"=>"HK USP Compact"),
"kill 216"=> array( "Season Total"=>"14",
				"name"=>"Dubaku's henchman #3",
				"episode"=>"3:00pm-4:00pm",
				"weapon"=>"HK USP Compact"),
"kill 217"=> array( "Season Total"=>"15",
				"name"=>"Elemu",
				"episode"=>"3:00pm-4:00pm",
				"weapon"=>"HK USP Compact"),
"kill 218"=> array( "Season Total"=>"16",
				"name"=>"Dubaku's driver",
				"episode"=>"5:00pm-6:00pm",
				"weapon"=>"HK USP Compact"),
"kill 219"=> array( "Season Total"=>"17",
				"name"=>"Cimbe",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"HK USP Compact"),
"kill 220"=> array( "Season Total"=>"18",
				"name"=>"Benjamin Juma's soldier #1",
				"episode"=>"8:00pm-9:00pm",
				"weapon"=>"HK G36C"),
"kill 221"=> array( "Season Total"=>"19",
				"name"=>"Benjamin Juma's soldier #2",
				"episode"=>"8:00pm-9:00pm",
				"weapon"=>"HK G36C"),
"kill 222"=> array( "Season Total"=>"20",
				"name"=>"Benjamin Juma's soldier #3",
				"episode"=>"8:00pm-9:00pm",
				"weapon"=>"HK USP Compact"),
"kill 223"=> array( "Season Total"=>"21",
				"name"=>"Benjamin Juma's soldier #4",
				"episode"=>"8:00pm-9:00pm",
				"weapon"=>"HK USP Compact"),
"kill 224"=> array( "Season Total"=>"22",
				"name"=>"Ngozi",
				"episode"=>"8:00pm-9:00pm",
				"weapon"=>"HK USP Compact"),
"kill 225"=> array( "Season Total"=>"23",
				"name"=>"Benjamin Juma",
				"episode"=>"8:00pm-9:00pm",
				"weapon"=>"HK USP Compact"),
"kill 226"=> array( "Season Total"=>"24",
				"name"=>"John Quinn",
				"episode"=>"9:00pm-10:00pm",
				"weapon"=>"Screwdriver"),
"kill 227"=> array( "Season Total"=>"25",
				"name"=>"Cooper",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Mk 18 Mod 0"),
"kill 228"=> array( "Season Total"=>"26",
				"name"=>"Starkwood mercenary #1",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Mk 18 Mod 0"),
"kill 229"=> array( "Season Total"=>"27",
				"name"=>"Starkwood mercenary #2",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Mk 18 Mod 0"),
"kill 230"=> array( "Season Total"=>"28",
				"name"=>"Tony Almeida med tech #1",
				"episode"=>"6:00am-7:00am",
				"weapon"=>"Scalpel"),
"kill 231"=> array( "Season Total"=>"29",
				"name"=>"Tony Almeida med tech #2",
				"episode"=>"6:00am-7:00am",
				"weapon"=>"Scalpel"),
"kill 232"=> array( "Season Total"=>"30",
				"name"=>"Dr. Levinson",
				"episode"=>"6:00am-7:00am",
				"weapon"=>"Broken neck"),
"kill 233"=> array( "Season Total"=>"1",
				"name"=>"Red Square spotter",
				"episode"=>"4:00pm-5:00pm",
				"weapon"=>"Fire axe"),
"kill 234"=> array( "Season Total"=>"2",
				"name"=>"Red Square sniper",
				"episode"=>"4:00pm-5:00pm",
				"weapon"=>"Fall"),
"kill 235"=> array( "Season Total"=>"3",
				"name"=>"Davros",
				"episode"=>"7:00pm-8:00pm",
				"weapon"=>"HK USP Compact"),
"kill 236"=> array( "Season Total"=>"4",
				"name"=>"Lugo Elson",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"Knife"),
"kill 237"=> array( "Season Total"=>"5",
				"name"=>"Laitanan's henchman",
				"episode"=>"10:00pm-11:00pm",
				"weapon"=>"HK USP Compact"),
"kill 238"=> array( "Season Total"=>"6",
				"name"=>"Dimitri",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"Broken neck"),
"kill 239"=> array( "Season Total"=>"7",
				"name"=>"Bazhaev's henchman #1",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"Paragon OTF ATKO Model 10 TP"),
"kill 240"=> array( "Season Total"=>"8",
				"name"=>"Bazhaev's henchman #2",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"Beretta M92FS"),
"kill 241"=> array( "Season Total"=>"9",
				"name"=>"Andre",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"Beretta M92FS"),
"kill 242"=> array( "Season Total"=>"10",
				"name"=>"Bazhaev's henchman #3",
				"episode"=>"11:00pm-12:00am",
				"weapon"=>"Steyr SPP"),
"kill 243"=> array( "Season Total"=>"11",
				"name"=>"Hamid",
				"episode"=>"4:00am-5:00am",
				"weapon"=>"M4A1 Carbine"),
"kill 244"=> array( "Season Total"=>"12",
				"name"=>"Ali's spotter",
				"episode"=>"4:00am-5:00am",
				"weapon"=>"M4A1 Carbine"),
"kill 245"=> array( "Season Total"=>"13",
				"name"=>"Mathis",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 246"=> array( "Season Total"=>"14",
				"name"=>"Donner",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 247"=> array( "Season Total"=>"15",
				"name"=>"Brucker's commando #3",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 248"=> array( "Season Total"=>"16",
				"name"=>"Brucker's commando #4",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 249"=> array( "Season Total"=>"17",
				"name"=>"Brucker's commando #5",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 250"=> array( "Season Total"=>"18",
				"name"=>"Brucker's commando #6",
				"episode"=>"5:00am-6:00am",
				"weapon"=>"HK USP Compact"),
"kill 251"=> array( "Season Total"=>"19",
				"name"=>"Mehran terrorist",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"HK USP Compact with silencer"),
"kill 252"=> array( "Season Total"=>"20",
				"name"=>"Ahman",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"HK USP Compact with silencer"),
"kill 253"=> array( "Season Total"=>"21",
				"name"=>"Navid",
				"episode"=>"7:00am-8:00am",
				"weapon"=>"HK USP Compact with silencer"),
"kill 254"=> array( "Season Total"=>"22",
				"name"=>"Mark Bledsoe",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"HK USP Compact"),
"kill 255"=> array( "Season Total"=>"23",
				"name"=>"Security contractor #1",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"HK USP Compact"),
"kill 256"=> array( "Season Total"=>"24",
				"name"=>"Security contractor #2",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"HK USP Compact"),
"kill 257"=> array( "Season Total"=>"25",
				"name"=>"Security contractor #3",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"Taurus Judge Public Defender"),
"kill 258"=> array( "Season Total"=>"26",
				"name"=>"Dana Walsh",
				"episode"=>"11:00am-12:00pm",
				"weapon"=>"HK USP Compact"),
"kill 259"=> array( "Season Total"=>"27",
				"name"=>"Pavel's operative #1",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 260"=> array( "Season Total"=>"28",
				"name"=>"Pavel's operative #2",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 261"=> array( "Season Total"=>"29",
				"name"=>"Pavel's operative #3",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 262"=> array( "Season Total"=>"30",
				"name"=>"Pavel's operative #4",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"HK USP Compact with silencer"),
"kill 263"=> array( "Season Total"=>"31",
				"name"=>"Pavel Tokarev",
				"episode"=>"12:00pm-1:00pm",
				"weapon"=>"Microtech Combat Troodon"),
"kill 264"=> array( "Season Total"=>"32",
				"name"=>"Novakovich's bodyguard #1",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"HK USP Compact"),
"kill 265"=> array( "Season Total"=>"33",
				"name"=>"Novakovich's bodyguard #2",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"DKW Sandshark"),
"kill 266"=> array( "Season Total"=>"34",
				"name"=>"Novakovich's bodyguard #3",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"Remington 870"),
"kill 267"=> array( "Season Total"=>"35",
				"name"=>"Novakovich's bodyguard #4",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"Remington 870"),
"kill 268"=> array( "Season Total"=>"36",
				"name"=>"Novakovich's bodyguard #5",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"HK USP Compact"),
"kill 269"=> array( "Season Total"=>"37",
				"name"=>"Mikhail Novakovich",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"Fireplace poker"),
"kill 270"=> array( "Season Total"=>"38",
				"name"=>"Berkov",
				"episode"=>"1:00pm-2:00pm",
				"weapon"=>"HK USP Compact"),
"kill 271"=> array( "Season Total"=>"1",
				"name"=>"Basher's thug #1",
				"episode"=>"12:45pm",
				"weapon"=>"HK P30"),
"kill 272"=> array( "Season Total"=>"2",
				"name"=>"Basher's thug #2",
				"episode"=>"12:46pm",
				"weapon"=>"Knife"),
"kill 273"=> array( "Season Total"=>"3",
				"name"=>"Karl Rask's henchman #1",
				"episode"=>"4:53pm",
				"weapon"=>"Steyr M9-A1"),
"kill 274"=> array( "Season Total"=>"4",
				"name"=>"Karl Rask's henchman #2",
				"episode"=>"4:53pm",
				"weapon"=>"Steyr M9-A1"),
"kill 275"=> array( "Season Total"=>"5",
				"name"=>"Karl Rask's henchman #3",
				"episode"=>"4:54pm",
				"weapon"=>"Explosion"),
"kill 276"=> array( "Season Total"=>"6",
				"name"=>"Al-Harazi guard #1",
				"episode"=>"7:23pm",
				"weapon"=>"HK P30"),
"kill 277"=> array( "Season Total"=>"7",
				"name"=>"Al-Harazi guard #2",
				"episode"=>"7:23pm",
				"weapon"=>"HK P30"),
"kill 278"=> array( "Season Total"=>"8",
				"name"=>"Ian Al-Harazi",
				"episode"=>"7:27pm",
				"weapon"=>"Fall"),
"kill 279"=> array( "Season Total"=>"9",
				"name"=>"Margot Al-Harazi",
				"episode"=>"7:28pm",
				"weapon"=>"Fall"),
"kill 280"=> array( "Season Total"=>"10",
				"name"=>"Russian driver",
				"episode"=>"8:57pm",
				"weapon"=>"HK P30"),
"kill 281"=> array( "Season Total"=>"11",
				"name"=>"Russian operative #1",
				"episode"=>"9:04pm",
				"weapon"=>"HK P30"),
"kill 282"=> array( "Season Total"=>"12",
				"name"=>"Russian operative leader",
				"episode"=>"9:04pm",
				"weapon"=>"HK P30"),
"kill 283"=> array( "Season Total"=>"13",
				"name"=>"Russian operatives #3",
				"episode"=>"9:06pm",
				"weapon"=>"Explosion"),
"kill 284"=> array( "Season Total"=>"14",
				"name"=>"Russian operatives #4",
				"episode"=>"9:06pm",
				"weapon"=>"Explosion"),
"kill 285"=> array( "Season Total"=>"15",
				"name"=>"Anatol Stolnavich's gatekeeper",
				"episode"=>"9:53pm",
				"weapon"=>"HK P30"),
"kill 286"=> array( "Season Total"=>"16",
				"name"=>"Stolnavich's bodyguard #1",
				"episode"=>"9:54pm",
				"weapon"=>"HK P30"),
"kill 287"=> array( "Season Total"=>"17",
				"name"=>"Stolnavich's bodyguard #2",
				"episode"=>"9:54pm",
				"weapon"=>"HK P30"),
"kill 288"=> array( "Season Total"=>"18",
				"name"=>"Stolnavich's bodyguard #3",
				"episode"=>"9:54pm",
				"weapon"=>"HK P30"),
"kill 289"=> array( "Season Total"=>"19",
				"name"=>"Russian sentry #1",
				"episode"=>"10:25pm",
				"weapon"=>"HK416"),
"kill 290"=> array( "Season Total"=>"20",
				"name"=>"Russian sentry #2",
				"episode"=>"10:26pm",
				"weapon"=>"HK416"),
"kill 291"=> array( "Season Total"=>"21",
				"name"=>"Chinese sentry #1",
				"episode"=>"10:26pm",
				"weapon"=>"HK416"),
"kill 292"=> array( "Season Total"=>"22",
				"name"=>"Chinese sentry #2",
				"episode"=>"10:27pm",
				"weapon"=>"HK416"),
"kill 293"=> array( "Season Total"=>"23",
				"name"=>"Chinese sentry #3",
				"episode"=>"10:27pm",
				"weapon"=>"HK416"),
"kill 294"=> array( "Season Total"=>"24",
				"name"=>"Cheng's henchmen #1",
				"episode"=>"10:39pm",
				"weapon"=>"HK416"),
"kill 295"=> array( "Season Total"=>"25",
				"name"=>"Cheng's henchmen #2",
				"episode"=>"10:39pm",
				"weapon"=>"HK416"),
"kill 296"=> array( "Season Total"=>"26",
				"name"=>"Cheng's henchmen #3",
				"episode"=>"10:39pm",
				"weapon"=>"HK416"),
"kill 297"=> array( "Season Total"=>"27",
				"name"=>"Cheng's henchmen #4",
				"episode"=>"10:39pm",
				"weapon"=>"HK416"),
"kill 298"=> array( "Season Total"=>"28",
				"name"=>"Cheng's henchmen #5",
				"episode"=>"10:39pm",
				"weapon"=>"HK416"),
"kill 299"=> array( "Season Total"=>"29",
				"name"=>"Cheng's henchmen #6",
				"episode"=>" 10:39pm",
				"weapon"=>"HK416"),
"kill 300"=> array( "Season Total"=>"30",
				"name"=>"Cheng's henchmen #7",
				"episode"=>"10:39pm",
				"weapon"=>"HK416"),
"kill 301"=> array( "Season Total"=>"31",
				"name"=>"Cheng's henchmen #8",
				"episode"=>"10:39pm",
				"weapon"=>"HK416"),
"kill 302"=> array( "Season Total"=>"32",
				"name"=>"Cheng Zhi's henchman #9",
				"episode"=>"10:39pm",
				"weapon"=>"HK P30"),
"kill 303"=> array( "Season Total"=>"33",
				"name"=>"Cheng Zhi's henchman #10",
				"episode"=>"10:39pm",
				"weapon"=>"HK P30"),
"kill 304"=> array( "Season Total"=>"34",
				"name"=>"Cheng Zhi's henchman #11",
				"episode"=>"10:39pm",
				"weapon"=>"HK P30"),
"kill 305"=> array( "Season Total"=>"35",
				"name"=>"Cheng Zhi's henchman #12",
				"episode"=>"10:39pm",
				"weapon"=>"Cleaver"),
"kill 306"=> array( "Season Total"=>"36",
				"name"=>"Cheng's technician",
				"episode"=>"10:40pm",
				"weapon"=>"HK P30"),
"kill 307"=> array( "Season Total"=>"37",
				"name"=>"Cheng's henchman #13",
				"episode"=>"10:40pm",
				"weapon"=>"HK P30"),
"kill 308"=> array( "Season Total"=>"38",
				"name"=>"Cheng's henchman #14",
				"episode"=>"10:40pm",
				"weapon"=>"HK P30"),
"kill 309"=> array( "Season Total"=>"39",
				"name"=>"Cheng Zhi",
				"episode"=>"10:42pm",
				"weapon"=>"Katana")
);


echo "<!DOCTYPE html>
<html>
	<head>
		<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js'></script>
		<script src='got.js'></script>
		<link rel='stylesheet' href='got.css'>
		<link rel='stylesheet' href='gotmob.css'>
		<meta name='viewport' content='width=device-width, initial-scale=1.0'/>
	</head>
	<body>";

$keys = array_keys($jackkills);

for($i = 0; $i < count($jackkills); $i++) {
	
	echo "<img id='". $keys[$i] . "' class='killskulls'src='skull.jpg'> <br> <p id='killcount'>". $keys[$i] ."</p>";
    foreach($jackkills[$keys[$i]] as $key => $value) 
    {
		echo "<p class='".$key . "' id='".$value."'>" .$key.":".$value. "</p>";
    }
    echo "<br>";
};

echo "</body>
	</html>";
?>